unopt: speed_test.cc top_sort.cc
	g++ -O0 -std=c++0x -o TopSortSpeedTest speed_test.cc top_sort.cc
opt: speed_test.cc top_sort.cc
	g++ -O3 -std=c++0x -o TopSortSpeedTest speed_test.cc top_sort.cc
clean:
	rm TopSortSpeedTest
